### ISSUE TITLE
D10.2.3 errors

### ISSUE THREAD

**Issue by limelect** [digitalw0lf/hextor#36]
D10.2.3
Could not find uActiveScript;
ctx.NotWriteEmptyField := ANotWriteEmptyField; no such thing NotWriteEmptyField
may be more?

**Comment by digitalw0lf** [comment]
uActiveScript.pas is in https://github.com/digitalw0lf/dwfunits repo

ctx.NotWriteEmptyField: you should use https://github.com/fainspace/superobject.git fork instead of original superobject.

But, currently Hextor is not prepared to be compiled by everyone. It has some non-opensource dependencies from my commercial projects. So I don't think you will be able to build it, sorry.

**Comment by limelect** [comment]
Ok, thanks.
Can you plz then make a portable version (only exe no installation)?

**Comment by digitalw0lf** [comment]
[HextorExe.zip](https://github.com/digitalw0lf/hextor/files/9010660/HextorExe.zip)
These are the same files that are created by installer. Is it ok or do you need a true "portable" version that does not creates any settings files when run on user machine? I'm planning to implement it in next version

**Comment by limelect** [comment]
Thanks
